#ifndef ALCHEMY_ICLASS_H
#define ALCHEMY_ICLASS_H

#include "igroup.h"

typedef enum {
    __reserved, /**/
    class_undefined,
    __unallocated, /**/
    class_unallocated,
    __dataProcessingImmediate, /**/
    class_pcRelativeAddressing,
    class_addSubtractImmediate,
    class_addSubtractImmediateTags,
    class_logicalImmediate,
    class_moveWideImmediate,
    class_bitfield,
    class_extract,
    __branchesAndExceptions, /**/
    class_conditionalBranchImmediate,
    class_exceptionGeneration,
    class_systemInstructionsRegister,
    class_hints,
    class_barriers,
    class_pstate,
    class_systemInstructions,
    class_SystemRegisterMove,
    class_unconditionalBranchRegister,
    class_unconditionalBranchImmediate,
    class_compareAndBranchImmediate,
    class_testAndBranchImmediate,
    __loadsAndStores, /**/
    class_simdLoadStoreMultiple,
    class_simdLoadStoreMultiplePostIndex,
    class_simdLoadStoreSingle,
    class_simdLoadStoreSinglePostIndex,
    class_loadStoreMemoryTags,
    class_loadStoreExclusive,
    class_LDAPR,
    class_loadRegisterLiteral,
    class_loadStorePairNoAllocate,
    class_loadStorePairPostIndex,
    class_loadStorePairOffset,
    class_loadStorePairPreIndex,
    class_loadStoreRegister,
    class_loadStoreRegisterPostIndex,
    class_loadStoreRegisterUnprivileged,
    class_loadStoreRegisterPreIndex,
    class_atomicOperations,
    class_loadStoreRegisterOffset,
    class_loadStoreRegisterPac,
    class_loadStoreRegisterUnsigned,
    __dataProcessing, /**/
    class_dataProcessing2Source,
    class_dataProcessing1Source,
    class_logicalShifted,
    class_addSubShifted,
    class_addSubExtended,
    class_addSubCarry,
    class_rotateRightFlags,
    class_evalFlags,
    class_conditionalCompareRegister,
    class_conditionalCompareImmediate,
    class_conditionalSelect,
    class_dataProcessing3Source,
    __floatAndSIMD, /**/
    class_cryptoAES,
    class_crypto3SHA,
    class_crypto2SHA,
    class_simdScalarCopy,
    class_simdScalarThreeSameFP16,
    class_simdScalarTwoRegisterMiscFP16,
    class_simdScalarThreeSameExtra,
    class_simdScalarTwoRegisterMisc,
    class_simdScalarPairwise,
    class_simdScalarThreeDifferent,
    class_simdScalarThreeSame,
    class_simdScalarShiftImmediate,
    class_simdScalarIndexedElement,
    class_simdTableLookup,
    class_simdPermute,
    class_simdExtract,
    class_simdCopy,
    class_simdThreeSameFP16,
    class_simdTwoRegisterMiscFP16,
    class_simdThreeRegisterExtension,
    class_simdTwoRegisterMisc,
    class_simdAcrossLanes,
    class_simdThreeDifferent,
    class_simdThreeSame,
    class_simdModifiedImmediate,
    class_simdShiftImmediate,
    class_simdVectorIndexedElement,
    class_cryptoThreeRegisterImm2,
    class_cryptoThreeRegisterSHA512,
    class_cryptoFourRegister,
    class_cryptoTwoRegisterSHA512,
    class_convertFloatFixed,
    class_convertFloatInteger,
    class_floatDataProcessing1Source,
    class_floatCompare,
    class_floatImmediate,
    class_floatConditionalCompare,
    class_floatDataProcessing2Source,
    class_floatConditionalSelect,
    class_floatDataProcessing3Source,
} IClass;

const char* iClass_debug[53];

IClass get_class(uint32_t instruction, IGroup group);

#endif //ALCHEMY_ICLASS_H
